repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort ML_for_Battery_Design/src
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black ML_for_Battery_Design/src
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8 ML_for_Battery_Design/src
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest
        types: [python]
        pass_filenames: false

      - id: pytest-cov-html-report
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov=ML_for_Battery_Design/src --cov-report=html --cov-fail-under=100
        types: [python]
        pass_filenames: false